### ISSUE TITLE
getting error genesis block hash mismatch

### ISSUE THREAD

**Issue by ch-mubarak** [seeleteam/go-seele#434]
getting error genesis block hash mismatch while running node.
![untitled](https://user-images.githubusercontent.com/34763421/43654788-10310848-976a-11e8-84d6-48048f3212e1.png)

**Comment by boqiu** [comment]
The workaround for such error is to delete the ${HOME}/.seele folder and try again.

As for the root cause, there are usually 2 cases:
1) You changed the node.json configuration file and launch the node program again.
2) You have run the node program before, and now sync up with the latest code and launch the node program again.

**Comment by boqiu** [comment]
BTW, the app folder on windows is C:\Users\{username}\.seele

**Comment by ch-mubarak** [comment]
thanks
